services:
  - type: web
    name: ripley-court-bot
    env: python
    buildCommand: |
      cd $(dirname "$0")
      pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class eventlet -w 1 -b 0.0.0.0:$PORT

  - type: cron
    name: update-embeddings-nightly
    env: python
    schedule: "0 0 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python make_embeddings.py

